# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
###############################################################################
#
# PURPOSE:
#   Normalize addresses according to the normalization standard used by Amazon
#   Ads for privacy enhanced identity resolution and data collaboration.
#
# USAGE:
#   1. Import AddressNormalizer
#   2. Instantiate AddressNormalizer with a country code, like this:
#      addressNormalizer = AddressNormalizer('FR')
#   3. Normalize text, like this:
#      addressNormalizer.normalize(text).normalizedAddress
#
# REFERENCE:
#   https://github.com/amzn/amazon-ads-advertiser-audience-normalization-sdk-py
#
###############################################################################
import hashlib
import re
from re import finditer

NumberIndicators = [
    {"NUM": "NUMBER"},
    {"NÚMERO": "NUMBER"},
    {"NÚM": "NUMBER"},
    {"NUMERO": "NUMBER"},
    {"#": "NUMBER"},
    {"NO": "NUMBER"},
]

DirectionalWords = [
    {"EAST": "E"},
    {"E": "E"},
    {"NORTH": "N"},
    {"N": "N"},
    {"SOUTH": "S"},
    {"S": "S"},
    {"SO": "S"},
    {"NORTHEAST": "NE"},
    {"NE": "NE"},
    {"NORTHWEST": "NW"},
    {"NW": "NW"},
    {"SOUTHEAST": "SE"},
    {"SE": "SE"},
    {"SOUTHWEST": "SW"},
    {"SW": "SW"},
]

DefaultStreetSuffixes = [
    {"AVENUE": "AVE"},
    {"AVE": "AVE"},
    {"BOULED": "BLVD"},
    {"BLVD": "BLVD"},
    {"CIRCLE": "CIR"},
    {"CIR": "CIR"},
    {"CIRCLES": "CIRS"},
    {"CIRS": "CIRS"},
    {"COURT": "CT"},
    {"CT": "CT"},
    {"CENTRE": "CTR"},
    {"CENTER": "CTR"},
    {"CTR": "CTR"},
    {"DRIVE": "DR"},
    {"DR": "DR"},
    {"FREEWAY": "FWY"},
    {"FRWY": "FWY"},
    {"FWY": "FWY"},
    {"HIGHWAY": "HWY"},
    {"HWY": "HWY"},
    {"LANE": "LN"},
    {"LN": "LN"},
    {"PARKS": "PARK"},
    {"PARK": "PARK"},
    {"PARKWAYS": "PKWY"},
    {"PKY": "PKWY"},
    {"PKWAY": "PKWY"},
    {"PKWYS": "PKWY"},
    {"PARKWAY": "PKWY"},
    {"PARKWY": "PKWY"},
    {"PKWY": "PKWY"},
    {"PLACE": "PL"},
    {"PL": "PL"},
    {"PLAZA": "PLZ"},
    {"PLZA": "PLZ"},
    {"PLZ": "PLZ"},
    {"ROAD": "RD"},
    {"RD": "RD"},
    {"SQUARE": "SQ"},
    {"SQU": "SQ"},
    {"SQR": "SQ"},
    {"SQ": "SQ"},
    {"STREET": "ST"},
    {"STR": "ST"},
    {"ST": "ST"},
]

USStreetSuffixes = [
    {"ALLEY": "ALY"},
    {"ALLEE": "ALY"},
    {"ALLY": "ALY"},
    {"ALY": "ALY"},
    {"ANNEX": "ANX"},
    {"ANNX": "ANX"},
    {"ANEX": "ANX"},
    {"ANX": "ANX"},
    {"ARCADE": "ARC"},
    {"ARC": "ARC"},
    {"AV": "AVE"},
    {"AVENU": "AVE"},
    {"AVENUE": "AVE"},
    {"AVEN": "AVE"},
    {"AVNUE": "AVE"},
    {"AVN": "AVE"},
    {"AVE": "AVE"},
    {"BEACH": "BCH"},
    {"BCH": "BCH"},
    {"BURG": "BG"},
    {"BG": "BG"},
    {"BURGS": "BGS"},
    {"BGS": "BGS"},
    {"BLUFF": "BLF"},
    {"BLUF": "BLF"},
    {"BLF": "BLF"},
    {"BLUFFS": "BLFS"},
    {"BLFS": "BLFS"},
    {"BOULV": "BLVD"},
    {"BOULED": "BLVD"},
    {"BOUL": "BLVD"},
    {"BLVD": "BLVD"},
    {"BEND": "BND"},
    {"BND": "BND"},
    {"BRANCH": "BR"},
    {"BRNCH": "BR"},
    {"BR": "BR"},
    {"BRDGE": "BRG"},
    {"BRIDGE": "BRG"},
    {"BRG": "BRG"},
    {"BROOK": "BRK"},
    {"BRK": "BRK"},
    {"BROOKS": "BRKS"},
    {"BRKS": "BRKS"},
    {"BOT": "BTM"},
    {"BOTTM": "BTM"},
    {"BOTTOM": "BTM"},
    {"BTM": "BTM"},
    {"BYPASS": "BYP"},
    {"BYPAS": "BYP"},
    {"BYPS": "BYP"},
    {"BYPA": "BYP"},
    {"BYP": "BYP"},
    {"BAYOU": "BYU"},
    {"BAYOO": "BYU"},
    {"BYU": "BYU"},
    {"CRCL": "CIR"},
    {"CRCLE": "CIR"},
    {"CIRCLE": "CIR"},
    {"CIRCL": "CIR"},
    {"CIRC": "CIR"},
    {"CIR": "CIR"},
    {"CIRCLES": "CIRS"},
    {"CIRS": "CIRS"},
    {"CLUB": "CLB"},
    {"CLB": "CLB"},
    {"CLIFF": "CLF"},
    {"CLF": "CLF"},
    {"CLIFFS": "CLFS"},
    {"CLFS": "CLFS"},
    {"COMMON": "CMN"},
    {"CMN": "CMN"},
    {"COMMONS": "CMNS"},
    {"CMNS": "CMNS"},
    {"CORNER": "COR"},
    {"COR": "COR"},
    {"CORNERS": "CORS"},
    {"CORS": "CORS"},
    {"CMP": "CP"},
    {"CAMP": "CP"},
    {"CP": "CP"},
    {"CAPE": "CPE"},
    {"CPE": "CPE"},
    {"CRESCENT": "CRES"},
    {"CRSNT": "CRES"},
    {"CRSENT": "CRES"},
    {"CRES": "CRES"},
    {"CREEK": "CRK"},
    {"CRK": "CRK"},
    {"COURSE": "CRSE"},
    {"CRSE": "CRSE"},
    {"CREST": "CRST"},
    {"CRST": "CRST"},
    {"CAUSEWAY": "CSWY"},
    {"CAUSWA": "CSWY"},
    {"CSWY": "CSWY"},
    {"COURT": "CT"},
    {"CT": "CT"},
    {"CENTR": "CTR"},
    {"CEN": "CTR"},
    {"CNTR": "CTR"},
    {"CENTRE": "CTR"},
    {"CNTER": "CTR"},
    {"CENT": "CTR"},
    {"CENTER": "CTR"},
    {"CTR": "CTR"},
    {"CENTERS": "CTRS"},
    {"CTRS": "CTRS"},
    {"COURTS": "CTS"},
    {"CTS": "CTS"},
    {"CURVE": "CURV"},
    {"CURV": "CURV"},
    {"COVE": "CV"},
    {"CV": "CV"},
    {"COVES": "CVS"},
    {"CVS": "CVS"},
    {"CNYN": "CYN"},
    {"CANYN": "CYN"},
    {"CANYON": "CYN"},
    {"CYN": "CYN"},
    {"DALE": "DL"},
    {"DL": "DL"},
    {"DAM": "DM"},
    {"DM": "DM"},
    {"DRIV": "DR"},
    {"DRIVE": "DR"},
    {"DRV": "DR"},
    {"DR": "DR"},
    {"DRIVES": "DRS"},
    {"DRS": "DRS"},
    {"DVD": "DV"},
    {"DIVIDE": "DV"},
    {"DIV": "DV"},
    {"DV": "DV"},
    {"ESTATE": "EST"},
    {"EST": "EST"},
    {"ESTATES": "ESTS"},
    {"ESTS": "ESTS"},
    {"EXPRESSWAY": "EXPY"},
    {"EXPW": "EXPY"},
    {"EXPR": "EXPY"},
    {"EXP": "EXPY"},
    {"EXPRESS": "EXPY"},
    {"EXPY": "EXPY"},
    {"EXTENSION": "EXT"},
    {"EXTN": "EXT"},
    {"EXTNSN": "EXT"},
    {"EXT": "EXT"},
    {"EXTENSIONS": "EXTS"},
    {"EXTS": "EXTS"},
    {"FALL": "FALL"},
    {"FALL": "FALL"},
    {"FIELD": "FLD"},
    {"FLD": "FLD"},
    {"FIELDS": "FLDS"},
    {"FLDS": "FLDS"},
    {"FALLS": "FLS"},
    {"FLS": "FLS"},
    {"FLAT": "FLT"},
    {"FLT": "FLT"},
    {"FLATS": "FLTS"},
    {"FLTS": "FLTS"},
    {"FORD": "FRD"},
    {"FRD": "FRD"},
    {"FORDS": "FRDS"},
    {"FRDS": "FRDS"},
    {"FORGE": "FRG"},
    {"FORG": "FRG"},
    {"FRG": "FRG"},
    {"FORGES": "FRGS"},
    {"FRGS": "FRGS"},
    {"FORK": "FRK"},
    {"FRK": "FRK"},
    {"FORKS": "FRKS"},
    {"FRKS": "FRKS"},
    {"FORESTS": "FRST"},
    {"FOREST": "FRST"},
    {"FRST": "FRST"},
    {"FRRY": "FRY"},
    {"FERRY": "FRY"},
    {"FRY": "FRY"},
    {"FORT": "FT"},
    {"FRT": "FT"},
    {"FT": "FT"},
    {"FREEWY": "FWY"},
    {"FRWAY": "FWY"},
    {"FREEWAY": "FWY"},
    {"FRWY": "FWY"},
    {"FWY": "FWY"},
    {"GRDEN": "GDN"},
    {"GARDEN": "GDN"},
    {"GRDN": "GDN"},
    {"GARDN": "GDN"},
    {"GDN": "GDN"},
    {"GARDENS": "GDNS"},
    {"GRDNS": "GDNS"},
    {"GDNS": "GDNS"},
    {"GDNS": "GDNS"},
    {"GLEN": "GLN"},
    {"GLN": "GLN"},
    {"GLENS": "GLNS"},
    {"GLNS": "GLNS"},
    {"GREEN": "GRN"},
    {"GRN": "GRN"},
    {"GREENS": "GRNS"},
    {"GRNS": "GRNS"},
    {"GROV": "GRV"},
    {"GROVE": "GRV"},
    {"GRV": "GRV"},
    {"GROVES": "GRVS"},
    {"GRVS": "GRVS"},
    {"GATWAY": "GTWY"},
    {"GATEWAY": "GTWY"},
    {"GATEWY": "GTWY"},
    {"GTWAY": "GTWY"},
    {"GTWY": "GTWY"},
    {"HRBOR": "HBR"},
    {"HARBOR": "HBR"},
    {"HARB": "HBR"},
    {"HARBR": "HBR"},
    {"HBR": "HBR"},
    {"HARBORS": "HBRS"},
    {"HBRS": "HBRS"},
    {"HILL": "HL"},
    {"HL": "HL"},
    {"HILLS": "HLS"},
    {"HLS": "HLS"},
    {"HLLW": "HOLW"},
    {"HOLWS": "HOLW"},
    {"HOLLOW": "HOLW"},
    {"HOLLOWS": "HOLW"},
    {"HOLW": "HOLW"},
    {"HEIGHTS": "HTS"},
    {"HT": "HTS"},
    {"HTS": "HTS"},
    {"HAVEN": "HVN"},
    {"HVN": "HVN"},
    {"HIGHWY": "HWY"},
    {"HIGHWAY": "HWY"},
    {"HIWY": "HWY"},
    {"HWAY": "HWY"},
    {"HIWAY": "HWY"},
    {"HWY": "HWY"},
    {"INLET": "INLT"},
    {"INLT": "INLT"},
    {"ISLAND": "IS"},
    {"ISLND": "IS"},
    {"IS": "IS"},
    {"ISLES": "ISLE"},
    {"ISLE": "ISLE"},
    {"ISLE": "ISLE"},
    {"ISLANDS": "ISS"},
    {"ISLNDS": "ISS"},
    {"ISS": "ISS"},
    {"JUNCTON": "JCT"},
    {"JCTN": "JCT"},
    {"JCTION": "JCT"},
    {"JUNCTN": "JCT"},
    {"JUNCTION": "JCT"},
    {"JCT": "JCT"},
    {"JCTNS": "JCTS"},
    {"JUNCTIONS": "JCTS"},
    {"JCTS": "JCTS"},
    {"KNOLL": "KNL"},
    {"KNOL": "KNL"},
    {"KNL": "KNL"},
    {"KNOLLS": "KNLS"},
    {"KNLS": "KNLS"},
    {"KEY": "KY"},
    {"KY": "KY"},
    {"KEYS": "KYS"},
    {"KYS": "KYS"},
    {"LAND": "LAND"},
    {"LAND": "LAND"},
    {"LOCK": "LCK"},
    {"LCK": "LCK"},
    {"LOCKS": "LCKS"},
    {"LCKS": "LCKS"},
    {"LODGE": "LDG"},
    {"LODG": "LDG"},
    {"LDGE": "LDG"},
    {"LDG": "LDG"},
    {"LOAF": "LF"},
    {"LF": "LF"},
    {"LIGHT": "LGT"},
    {"LGT": "LGT"},
    {"LIGHTS": "LGTS"},
    {"LGTS": "LGTS"},
    {"LAKE": "LK"},
    {"LK": "LK"},
    {"LAKES": "LKS"},
    {"LKS": "LKS"},
    {"LANE": "LN"},
    {"LN": "LN"},
    {"LANDING": "LNDG"},
    {"LNDNG": "LNDG"},
    {"LNDG": "LNDG"},
    {"LOOP": "LOOP"},
    {"LOOPS": "LOOP"},
    {"LOOP": "LOOP"},
    {"MALL": "MALL"},
    {"MALL": "MALL"},
    {"MEADOW": "MDW"},
    {"MDW": "MDW"},
    {"MEADOWS": "MDWS"},
    {"MDW": "MDWS"},
    {"MEDOWS": "MDWS"},
    {"MDWS": "MDWS"},
    {"MEWS": "MEWS"},
    {"MEWS": "MEWS"},
    {"MILL": "ML"},
    {"ML": "ML"},
    {"MILLS": "MLS"},
    {"MLS": "MLS"},
    {"MANOR": "MNR"},
    {"MNR": "MNR"},
    {"MANORS": "MNRS"},
    {"MNRS": "MNRS"},
    {"MISSION": "MSN"},
    {"MSSN": "MSN"},
    {"MISSN": "MSN"},
    {"MSN": "MSN"},
    {"MNT": "MT"},
    {"MOUNT": "MT"},
    {"MT": "MT"},
    {"MNTN": "MTN"},
    {"MOUNTAIN": "MTN"},
    {"MOUNTIN": "MTN"},
    {"MNTAIN": "MTN"},
    {"MTIN": "MTN"},
    {"MTN": "MTN"},
    {"MOUNTAINS": "MTNS"},
    {"MTNS": "MTNS"},
    {"MOTORWAY": "MTWY"},
    {"MTWY": "MTWY"},
    {"NECK": "NCK"},
    {"NCK": "NCK"},
    {"OVERPASS": "OPAS"},
    {"OPAS": "OPAS"},
    {"ORCHARD": "ORCH"},
    {"ORCHRD": "ORCH"},
    {"ORCH": "ORCH"},
    {"OVAL": "OVAL"},
    {"OVL": "OVAL"},
    {"OVAL": "OVAL"},
    {"PRK": "PARK"},
    {"PARK": "PARK"},
    {"PARKS": "PARK"},
    {"PARK": "PARK"},
    {"PASS": "PASS"},
    {"PASS": "PASS"},
    {"PATHS": "PATH"},
    {"PATH": "PATH"},
    {"PATH": "PATH"},
    {"PIKE": "PIKE"},
    {"PIKES": "PIKE"},
    {"PIKE": "PIKE"},
    {"PARKWAYS": "PKWY"},
    {"PKY": "PKWY"},
    {"PKWAY": "PKWY"},
    {"PKWYS": "PKWY"},
    {"PARKWAY": "PKWY"},
    {"PARKWY": "PKWY"},
    {"PKWY": "PKWY"},
    {"PLACE": "PL"},
    {"PL": "PL"},
    {"PLAIN": "PLN"},
    {"PLN": "PLN"},
    {"PLAINS": "PLNS"},
    {"PLNS": "PLNS"},
    {"PLAZA": "PLZ"},
    {"PLZA": "PLZ"},
    {"PLZ": "PLZ"},
    {"PINE": "PNE"},
    {"PNE": "PNE"},
    {"PINES": "PNES"},
    {"PNES": "PNES"},
    {"PRR": "PR"},
    {"PRAIRIE": "PR"},
    {"PR": "PR"},
    {"PORT": "PRT"},
    {"PRT": "PRT"},
    {"PORTS": "PRTS"},
    {"PRTS": "PRTS"},
    {"PASSAGE": "PSGE"},
    {"PSGE": "PSGE"},
    {"POINT": "PT"},
    {"PT": "PT"},
    {"POINTS": "PTS"},
    {"PTS": "PTS"},
    {"RAD": "RADL"},
    {"RADIEL": "RADL"},
    {"RADIAL": "RADL"},
    {"RADL": "RADL"},
    {"RAMP": "RAMP"},
    {"RAMP": "RAMP"},
    {"ROAD": "RD"},
    {"RD": "RD"},
    {"RIDGE": "RDG"},
    {"RDGE": "RDG"},
    {"RDG": "RDG"},
    {"RIDGES": "RDGS"},
    {"RDGS": "RDGS"},
    {"ROADS": "RDS"},
    {"RDS": "RDS"},
    {"RIVER": "RIV"},
    {"RVR": "RIV"},
    {"RIVR": "RIV"},
    {"RIV": "RIV"},
    {"RANCH": "RNCH"},
    {"RNCHS": "RNCH"},
    {"RANCHES": "RNCH"},
    {"RNCH": "RNCH"},
    {"ROW": "ROW"},
    {"ROW": "ROW"},
    {"RAPID": "RPD"},
    {"RPD": "RPD"},
    {"RAPIDS": "RPDS"},
    {"RPDS": "RPDS"},
    {"REST": "RST"},
    {"RST": "RST"},
    {"ROUTE": "RTE"},
    {"RTE": "RTE"},
    {"RUE": "RUE"},
    {"RUE": "RUE"},
    {"RUN": "RUN"},
    {"RUN": "RUN"},
    {"SHOAL": "SHL"},
    {"SHL": "SHL"},
    {"SHOALS": "SHLS"},
    {"SHLS": "SHLS"},
    {"SHOAR": "SHR"},
    {"SHORE": "SHR"},
    {"SHR": "SHR"},
    {"SHORES": "SHRS"},
    {"SHRS": "SHRS"},
    {"SKYWAY": "SKWY"},
    {"SKWY": "SKWY"},
    {"SUMIT": "SMT"},
    {"SUMMIT": "SMT"},
    {"SUMITT": "SMT"},
    {"SMT": "SMT"},
    {"SPRNG": "SPG"},
    {"SPRING": "SPG"},
    {"SPNG": "SPG"},
    {"SPG": "SPG"},
    {"SPNGS": "SPGS"},
    {"SPRNGS": "SPGS"},
    {"SPRINGS": "SPGS"},
    {"SPGS": "SPGS"},
    {"SPURS": "SPUR"},
    {"SPUR": "SPUR"},
    {"SPUR": "SPUR"},
    {"SQRE": "SQ"},
    {"SQUARE": "SQ"},
    {"SQU": "SQ"},
    {"SQR": "SQ"},
    {"SQ": "SQ"},
    {"SQUARES": "SQS"},
    {"SQRS": "SQS"},
    {"SQS": "SQS"},
    {"STREET": "ST"},
    {"STR": "ST"},
    {"STRT": "ST"},
    {"ST": "ST"},
    {"STATION": "STA"},
    {"STN": "STA"},
    {"STATN": "STA"},
    {"STA": "STA"},
    {"STRAVEN": "STRA"},
    {"STRAV": "STRA"},
    {"STRVN": "STRA"},
    {"STRAVENUE": "STRA"},
    {"STRAVN": "STRA"},
    {"STRVNUE": "STRA"},
    {"STRA": "STRA"},
    {"STREME": "STRM"},
    {"STREAM": "STRM"},
    {"STRM": "STRM"},
    {"STREETS": "STS"},
    {"STS": "STS"},
    {"TERR": "TER"},
    {"TERRACE": "TER"},
    {"TER": "TER"},
    {"TURNPIKE": "TPKE"},
    {"TRNPK": "TPKE"},
    {"TURNPK": "TPKE"},
    {"TPKE": "TPKE"},
    {"TRK": "TRAK"},
    {"TRKS": "TRAK"},
    {"TRACKS": "TRAK"},
    {"TRACK": "TRAK"},
    {"TRAK": "TRAK"},
    {"TRACES": "TRCE"},
    {"TRACE": "TRCE"},
    {"TRCE": "TRCE"},
    {"TRAFFICWAY": "TRFY"},
    {"TRFY": "TRFY"},
    {"TRAILS": "TRL"},
    {"TRLS": "TRL"},
    {"TRAIL": "TRL"},
    {"TRL": "TRL"},
    {"TRLRS": "TRLR"},
    {"TRAILER": "TRLR"},
    {"TRLR": "TRLR"},
    {"THROUGHWAY": "TRWY"},
    {"TRWY": "TRWY"},
    {"TUNEL": "TUNL"},
    {"TUNNEL": "TUNL"},
    {"TUNNL": "TUNL"},
    {"TUNLS": "TUNL"},
    {"TUNNELS": "TUNL"},
    {"TUNL": "TUNL"},
    {"UNION": "UN"},
    {"UN": "UN"},
    {"UNIONS": "UNS"},
    {"UNS": "UNS"},
    {"UNDERPASS": "UPAS"},
    {"UPAS": "UPAS"},
    {"VIADCT": "VIA"},
    {"VIADUCT": "VIA"},
    {"VDCT": "VIA"},
    {"VIA": "VIA"},
    {"VISTA": "VIS"},
    {"VSTA": "VIS"},
    {"VIST": "VIS"},
    {"VST": "VIS"},
    {"VIS": "VIS"},
    {"VILLE": "VL"},
    {"VL": "VL"},
    {"VILL": "VLG"},
    {"VILLAGE": "VLG"},
    {"VILLAG": "VLG"},
    {"VILLIAGE": "VLG"},
    {"VILLG": "VLG"},
    {"VLG": "VLG"},
    {"VILLAGES": "VLGS"},
    {"VLGS": "VLGS"},
    {"VLLY": "VLY"},
    {"VALLEY": "VLY"},
    {"VALLY": "VLY"},
    {"VLY": "VLY"},
    {"VALLEYS": "VLYS"},
    {"VLYS": "VLYS"},
    {"VIEW": "VW"},
    {"VW": "VW"},
    {"VIEWS": "VWS"},
    {"VWS": "VWS"},
    {"WALK": "WALK"},
    {"WALKS": "WALK"},
    {"WALK": "WALK"},
    {"WALL": "WALL"},
    {"WALL": "WALL"},
    {"WAY": "WAY"},
    {"WY": "WAY"},
    {"WAY": "WAY"},
    {"WAYS": "WAYS"},
    {"WAYS": "WAYS"},
    {"WELL": "WL"},
    {"WL": "WL"},
    {"WELLS": "WLS"},
    {"WLS": "WLS"},
    {"CROSSING": "XING"},
    {"CRSSNG": "XING"},
    {"XING": "XING"},
    {"CROSSROAD": "XRD"},
    {"XRD": "XRD"},
    {"CROSSROADS": "XRDS"},
    {"XRDS": "XRDS"},
]

USSubBuildingDesignator = [
    {"APARTMENT": "APT"},
    {"APT": "APT"},
    {"APPT": "APT"},
    {"DEPARTMENT": "DEPT"},
    {"DEPT": "DEPT"},
    {"HANGER": "HNGR"},
    {"HNGR": "HNGR"},
    {"KEY": "KEY"},
    {"LOT": "LOT"},
    {"ROOM": "RM"},
    {"RM": "RM"},
    {"SLIP": "SLIP"},
    {"SPACE": "SPC"},
    {"SPC": "SPC"},
    {"SUITE": "STE"},
    {"STE": "STE"},
    {"STOP": "STOP"},
    {"TRAILER": "TRLR"},
    {"TRLR": "TRLR"},
    {"FLOOR": "FL"},
    {"FL": "FL"},
    {"UNIT": "UNIT"},
    {"PIER": "PIER"},
    {"BUILDING": "BLDG"},
    {"BLDG": "BLDG"},
    {"BASEMENT": "BSMT"},
    {"BSMT": "BSMT"},
    {"FRONT": "FRNT"},
    {"FRNT": "FRNT"},
    {"LOBBY": "LBBY"},
    {"LBBY": "LBBY"},
    {"LOWER": "LOWR"},
    {"LOWR": "LOWR"},
    {"OFFICE": "OFC"},
    {"OFC": "OFC"},
    {"PENTHOUSE": "PH"},
    {"PH": "PH"},
    {"REAR": "REAR"},
    {"SIDE": "SIDE"},
    {"UPPER": "UPPR"},
    {"UPPR": "UPPR"},
]

ITStreetPrefixes = [
    {"PIAZZA": "PIAZZA"},
    {"P.ZZA": "PIAZZA"},
    {"P.ZA": "PIAZZA"},
    {"PZZA": "PIAZZA"},
    {"PZA": "PIAZZA"},
    {"PIAZZALE": "PIAZZALE"},
    {"P.LE": "PIAZZALE"},
    {"PLE": "PIAZZALE"},
    {"PIAZZETTA": "PIAZZETTA"},
    {"P.TTA": "PIAZZETTA"},
    {"PTTA": "PIAZZETTA"},
    {"LARGO": "LARGO"},
    {"L.GO": "LARGO"},
    {"LGO": "LARGO"},
    {"LARGHETTO": "LARGHETTO"},
    {"VIA": "VIA"},
    {"V.": "VIA"},
    {"VIALE": "VIALE"},
    {"V.LE": "VIALE"},
    {"VLE": "VIALE"},
    {"CORSO": "CORSO"},
    {"C.SO": "CORSO"},
    {"CSO": "CORSO"},
    {"VICOLO": "VICOLO"},
    {"V.LO": "VICOLO"},
    {"VLO": "VICOLO"},
    {"VICOLETTO": "VICOLETTO"},
    {"VICO": "VICO"},
    {"STRADA": "STRADA"},
]

FRStreetDesignator = [
    {"ALLÉE": "ALLÉE"},
    {"ALLEE": "ALLÉE"},
    {"ALLÉES": "ALLÉES"},
    {"ALLEES": "ALLÉES"},
    {"AVENUE": "AVENUE"},
    {"AVE": "AVENUE"},
    {"BOULED": "BOULED"},
    {"BLVD": "BOULED"},
    {"CHEMIN": "CHEMIN"},
    {"CHE": "CHEMIN"},
    {"IMPASSE": "IMPASSE"},
    {"IMP": "IMPASSE"},
    {"LIEU": "LIEU"},
    {"LIEU-DIT": "LIEU-DIT"},
    {"MONTÉE": "MONTÉE"},
    {"MONTEE": "MONTÉE"},
    {"PASSAGE": "PASSAGE"},
    {"PLACE": "PLACE"},
    {"ROUTE": "ROUTE"},
    {"RTE": "ROUTE"},
    {"RUE": "RUE"},
]

ESStreetPrefixes = [
    {"AVENIDA": "AVENIDA"},
    {"AV.": "AVENIDA"},
    {"AVD.": "AVENIDA"},
    {"AVD": "AVENIDA"},
    {"AVDA.": "AVENIDA"},
    {"AUTOPISTA": "AUTOPISTA"},
    {"AUTO.": "AUTOPISTA"},
    {"CALZADA": "CALZADA"},
    {"CZADA.": "CALZADA"},
    {"MUELLE": "MUELLE"},
    {"MUELL.": "MUELLE"},
    {"PASAJE": "PASAJE"},
    {"PSAJE.": "PASAJE"},
    {"ALAMEDA": "ALAMEDA"},
    {"ALAM.": "ALAMEDA"},
    {"CALLIZO": "CALLIZO"},
    {"CLLZO.": "CALLIZO"},
    {"CALLEJA": "CALLEJA"},
    {"CLLJA.": "CALLEJA"},
    {"CALLE": "CALLE"},
    {"C/": "CALLE"},
    {"C.": "CALLE"},
    {"CL.": "CALLE"},
    {"C": "CALLE"},
    {"C\\": "CALLE"},
    {"CARRE": "CALLE"},
    {"CARRER": "CALLE"},
    {"CARRETERA": "CARRETERA"},
    {"CTRA.": "CARRETERA"},
    {"CARRERA": "CARRERA"},
    {"CRA.": "CARRERA"},
    {"CINTURÓN": "CINTURÓN"},
    {"CINT.": "CINTURÓN"},
    {"AUTOVÍA": "AUTOVÍA"},
    {"AUTOV.": "AUTOVÍA"},
    {"CARRETERÍN": "CARRETERÍN"},
    {"CTRIN.": "CARRETERÍN"},
    {"CAMINO": "CAMINO"},
    {"CMNO.": "CAMINO"},
    {"CNO.": "CAMINO"},
    {"CALLEJUELA": "CALLEJUELA"},
    {"CJLA.": "CALLEJUELA"},
    {"BULE": "BULE"},
    {"BULEV.": "BULE"},
    {"CARRIL": "CARRIL"},
    {"CRRIL.": "CARRIL"},
    {"PASADIZO": "PASADIZO"},
    {"PZO.": "PASADIZO"},
    {"ACCESO": "ACCESO"},
    {"ACCES.": "ACCESO"},
    {"CIRCUNVALACIÓN": "CIRCUNVALACIÓN"},
    {"CCVCN.": "CIRCUNVALACIÓN"},
    {"CALLEJÓN": "CALLEJÓN"},
    {"CALLEJ.": "CALLEJÓN"},
    {"CJON.": "CALLEJÓN"},
    {"CLLON.": "CALLEJÓN"},
    {"RÚA": "RÚA"},
    {"RAMBLA": "RAMBLA"},
    {"RBLA": "RAMBLA"},
    {"PASSEIG": "PASSEIG"},
    {"PG": "PASSEIG"},
    {"PASEO": "PASSEIG"},
    {"PS": "PASSEIG"},
    {"P": "PASSEIG"},
    {"PLAZA": "PLAZA"},
    {"PL": "PLAZA"},
    {"PLZA": "PLAZA"},
    {"PZA": "PLAZA"},
    {"RONDA": "RONDA"},
    {"RDA": "RONDA"},
    {"MOLL": "MOLL"},
    {"LUGAR": "LUGAR"},
    {"LG": "LUGAR"},
    {"URBANIZACIÓN": "URBANIZACIÓN"},
    {"URB": "URBANIZACIÓN"},
]

UKOrganizationSuffixes = [
    {"INC": "INC"},
    {"INC.": "INC"},
    {"LTD": "LTD"},
    {"LTD.": "LTD"},
    {"LIMITED": "LTD"},
    {"LLC": "LLC"},
    {"LLC.": "LLC"},
    {"LLP": "LLP"},
    {"LLP.": "LLP"},
    {"SERVICES": "SERVICES"},
    {"SERVICE": "SERVICE"},
    {"CLUB": "CLUB"},
]

UKStreetSuffixes = [
    {"ABBEY": "ABBEY"},
    {"ABER": "ABER"},
    {"ACRE": "ACRE"},
    {"ACRES": "ACRES"},
    {"ALLEY": "ALLEY"},
    {"ALY": "ALLEY"},
    {"ALLT": "ALLT"},
    {"APPROACH": "APPROACH"},
    {"ARCADE": "ARCADE"},
    {"ARCH": "ARCH"},
    {"ASH": "ASH"},
    {"AVE": "AVE"},
    {"AVENUE": "AVE"},
    {"AY": "AY"},
    {"BANC": "BANC"},
    {"BANK": "BANK"},
    {"BANKS": "BANKS"},
    {"BAR": "BAR"},
    {"BARN": "BARN"},
    {"BARNS": "BARNS"},
    {"BARRACKS": "BARRACKS"},
    {"BAY": "BAY"},
    {"BEACH": "BEACH"},
    {"BECK": "BECK"},
    {"BEECHES": "BEECHES"},
    {"BEND": "BEND"},
    {"BLUFF": "BLUFF"},
    {"BLVD": "BLVD"},
    {"BOULED": "BLVD"},
    {"BOROUGH": "BOROUGH"},
    {"BOTTOM": "BOTTOM"},
    {"BOW": "BOW"},
    {"BRAE": "BRAE"},
    {"BRAKE": "BRAKE"},
    {"BRANCH": "BRANCH"},
    {"BREAK": "BREAK"},
    {"BRIDGE": "BRIDGE"},
    {"BRIDLEWAY": "BRIDLEWAY"},
    {"BRINK": "BRINK"},
    {"BROADWAY": "BROADWAY"},
    {"BROOK": "BROOK"},
    {"BROOKS": "BROOKS"},
    {"BROW": "BROW"},
    {"BRYN": "BRYN"},
    {"BUILDINGS": "BUILDINGS"},
    {"BUNGALOWS": "BUNGALOWS"},
    {"BURN": "BURN"},
    {"BUSH": "BUSH"},
    {"BUTTS": "BUTTS"},
    {"BYPASS": "BYPASS"},
    {"BYWAY": "BYWAY"},
    {"CAE": "CAE"},
    {"CAMP": "CAMP"},
    {"CANAL": "CANAL"},
    {"CANOL": "CANOL"},
    {"CAPEL": "CAPEL"},
    {"CARRS": "CARRS"},
    {"CASTELL": "CASTELL"},
    {"CASTLE": "CASTLE"},
    {"CAUSEWAY": "CAUSEWAY"},
    {"CEFN": "CEFN"},
    {"CENTRAL": "CENTRAL"},
    {"CENTRE": "CENTRE"},
    {"CENTER": "CENTRE"},
    {"CTR": "CENTRE"},
    {"CHARE": "CHARE"},
    {"CHASE": "CHASE"},
    {"CHURCH": "CHURCH"},
    {"CIR": "CIR"},
    {"CIRCLE": "CIR"},
    {"CIRCUIT": "CIRCUIT"},
    {"CIRCUS": "CIRCUS"},
    {"CLIFF": "CLIFF"},
    {"CLIFFE": "CLIFFE"},
    {"CLIFFS": "CLIFFS"},
    {"CLOISTER": "CLOISTER"},
    {"CLOSE": "CLOSE"},
    {"CL": "CLOSE"},
    {"CLOUGH": "CLOUGH"},
    {"COED": "COED"},
    {"COMBE": "COMBE"},
    {"COMMON": "COMMON"},
    {"COMMONS": "COMMONS"},
    {"CONCOURSE": "CONCOURSE"},
    {"COOMBE": "COOMBE"},
    {"COPPICE": "COPPICE"},
    {"COPSE": "COPSE"},
    {"CORNER": "CORNER"},
    {"CORNERS": "CORNERS"},
    {"COTE": "COTE"},
    {"COTTAGES": "COTTAGES"},
    {"COURSE": "COURSE"},
    {"COURTS": "COURTS"},
    {"COURTYARD": "COURTYARD"},
    {"COVE": "COVE"},
    {"COVERT": "COVERT"},
    {"CRAIG": "CRAIG"},
    {"CREEK": "CREEK"},
    {"CREIGIAU": "CREIGIAU"},
    {"CRESCENT": "CRESCENT"},
    {"CREST": "CREST"},
    {"CROFT": "CROFT"},
    {"CROFTS": "CROFTS"},
    {"CROOK": "CROOK"},
    {"CROSS": "CROSS"},
    {"CROSSING": "CROSSING"},
    {"CROSSROADS": "CROSSROADS"},
    {"CT": "CT"},
    {"COURT": "CT"},
    {"CUT": "CUT"},
    {"CUTTING": "CUTTING"},
    {"CWM": "CWM"},
    {"CWRT": "CWRT"},
    {"DALE": "DALE"},
    {"DAM": "DAM"},
    {"DEAN": "DEAN"},
    {"DEANE": "DEANE"},
    {"DELL": "DELL"},
    {"DELPH": "DELPH"},
    {"DENE": "DENE"},
    {"DIKE": "DIKE"},
    {"DINGLE": "DINGLE"},
    {"DITCH": "DITCH"},
    {"DOCK": "DOCK"},
    {"DOWN": "DOWN"},
    {"DOWNS": "DOWNS"},
    {"DR": "DR"},
    {"DRIVE": "DR"},
    {"DRIFT": "DRIFT"},
    {"DRIV": "DRIV"},
    {"DRIVEWAY": "DRIVEWAY"},
    {"DROVE": "DROVE"},
    {"DYFFRYN": "DYFFRYN"},
    {"DYKE": "DYKE"},
    {"EDGE": "EDGE"},
    {"EGLWYS": "EGLWYS"},
    {"ELMS": "ELMS"},
    {"EMBANKMENT": "EMBANKMENT"},
    {"END": "END"},
    {"ERW": "ERW"},
    {"ESPLANADE": "ESPLANADE"},
    {"ESTATE": "ESTATE"},
    {"FAIR": "FAIR"},
    {"FAIRWAY": "FAIRWAY"},
    {"FALLS": "FALLS"},
    {"FARM": "FARM"},
    {"FELD": "FELD"},
    {"FELL": "FELL"},
    {"FEN": "FEN"},
    {"FERRY": "FERRY"},
    {"FFERM": "FFERM"},
    {"FFORDD": "FFORDD"},
    {"FFRWD": "FFRWD"},
    {"FFYNON": "FFYNON"},
    {"FIELD": "FIELD"},
    {"FIELDS": "FIELDS"},
    {"FIRS": "FIRS"},
    {"FLATS": "FLATS"},
    {"FLATTS": "FLATTS"},
    {"FOLD": "FOLD"},
    {"FOLLY": "FOLLY"},
    {"FOOT": "FOOT"},
    {"FOOTPATH": "FOOTPATH"},
    {"FORD": "FORD"},
    {"FOREST": "FOREST"},
    {"FORGE": "FORGE"},
    {"FORK": "FORK"},
    {"FORT": "FORT"},
    {"FRIARS": "FRIARS"},
    {"FRON": "FRON"},
    {"FRONT": "FRONT"},
    {"FURLONG": "FURLONG"},
    {"FURZE": "FURZE"},
    {"GABLES": "GABLES"},
    {"GAP": "GAP"},
    {"GARDEN": "GARDEN"},
    {"GARDENS": "GARDENS"},
    {"GARN": "GARN"},
    {"GARTH": "GARTH"},
    {"GATE": "GATE"},
    {"GATES": "GATES"},
    {"GATEWAY": "GATEWAY"},
    {"GHYLL": "GHYLL"},
    {"GILL": "GILL"},
    {"GLADE": "GLADE"},
    {"GLAS": "GLAS"},
    {"GLEBE": "GLEBE"},
    {"GLEN": "GLEN"},
    {"GLYN": "GLYN"},
    {"GRAIG": "GRAIG"},
    {"GRANGE": "GRANGE"},
    {"GREEN": "GREEN"},
    {"GREENS": "GREENS"},
    {"GROUND": "GROUND"},
    {"GROUNDS": "GROUNDS"},
    {"GROVE": "GROVE"},
    {"GROVES": "GROVES"},
    {"GULLY": "GULLY"},
    {"GWAUN": "GWAUN"},
    {"GWERN": "GWERN"},
    {"HAFOD": "HAFOD"},
    {"HALL": "HALL"},
    {"HALLS": "HALLS"},
    {"HALT": "HALT"},
    {"HAMLET": "HAMLET"},
    {"HANGER": "HANGER"},
    {"HARBOUR": "HARBOUR"},
    {"HATCH": "HATCH"},
    {"HAUGH": "HAUGH"},
    {"HAVEN": "HAVEN"},
    {"HAYES": "HAYES"},
    {"HAYS": "HAYS"},
    {"HEAD": "HEAD"},
    {"HEATH": "HEATH"},
    {"HEDGE": "HEDGE"},
    {"HEIGHT": "HEIGHT"},
    {"HEIGHTS": "HEIGHTS"},
    {"HEOL": "HEOL"},
    {"HERMITAGE": "HERMITAGE"},
    {"HEY": "HEY"},
    {"HEYS": "HEYS"},
    {"HIDE": "HIDE"},
    {"HIGHWAY": "HIGHWAY"},
    {"HILL": "HILL"},
    {"HILLOCK": "HILLOCK"},
    {"HILLS": "HILLS"},
    {"HOLE": "HOLE"},
    {"HOLLOW": "HOLLOW"},
    {"HOLM": "HOLM"},
    {"HOLME": "HOLME"},
    {"HOLT": "HOLT"},
    {"HOMES": "HOMES"},
    {"HOUSE": "HOUSE"},
    {"HOUSES": "HOUSES"},
    {"HUNT": "HUNT"},
    {"HURST": "HURST"},
    {"HYDE": "HYDE"},
    {"INGS": "INGS"},
    {"INTERCHANGE": "INTERCHANGE"},
    {"ISAF": "ISAF"},
    {"ISLAND": "ISLAND"},
    {"ISLE": "ISLE"},
    {"JUNCTION": "JUNCTION"},
    {"KEEP": "KEEP"},
    {"KEYS": "KEYS"},
    {"KILN": "KILN"},
    {"KILNS": "KILNS"},
    {"KNAP": "KNAP"},
    {"KNAPP": "KNAPP"},
    {"KNOLL": "KNOLL"},
    {"KNOLLS": "KNOLLS"},
    {"KNOWLE": "KNOWLE"},
    {"LAKE": "LAKE"},
    {"LAKES": "LAKES"},
    {"LAND": "LAND"},
    {"LANDING": "LANDING"},
    {"LANDS": "LANDS"},
    {"LANES": "LANES"},
    {"LAWN": "LAWN"},
    {"LAWNS": "LAWNS"},
    {"LEA": "LEA"},
    {"LEAP": "LEAP"},
    {"LEAS": "LEAS"},
    {"LEAZE": "LEAZE"},
    {"LEES": "LEES"},
    {"LEIGH": "LEIGH"},
    {"LEY": "LEY"},
    {"LEYES": "LEYES"},
    {"LEYS": "LEYS"},
    {"LINE": "LINE"},
    {"LINK": "LINK"},
    {"LLAN": "LLAN"},
    {"LLWYN": "LLWYN"},
    {"LLYN": "LLYN"},
    {"LLYS": "LLYS"},
    {"LN": "LN"},
    {"LANE": "LN"},
    {"LOCK": "LOCK"},
    {"LOCKS": "LOCKS"},
    {"LODE": "LODE"},
    {"LODGE": "LODGE"},
    {"LONEY": "LONEY"},
    {"LOOKOUT": "LOOKOUT"},
    {"LOOP": "LOOP"},
    {"MAEN": "MAEN"},
    {"MAES": "MAES"},
    {"MALL": "MALL"},
    {"MALONE": "MALONE"},
    {"MANOR": "MANOR"},
    {"MANSIONS": "MANSIONS"},
    {"MARG": "MARG"},
    {"MARKET": "MARKET"},
    {"MARSH": "MARSH"},
    {"MAWR": "MAWR"},
    {"MAZE": "MAZE"},
    {"MEAD": "MEAD"},
    {"MEADOW": "MEADOW"},
    {"MEADOWS": "MEADOWS"},
    {"MEADS": "MEADS"},
    {"MEANDER": "MEANDER"},
    {"MEET": "MEET"},
    {"MERE": "MERE"},
    {"MEW": "MEW"},
    {"MEWS": "MEWS"},
    {"MILE": "MILE"},
    {"MILL": "MILL"},
    {"MILLS": "MILLS"},
    {"MOAT": "MOAT"},
    {"MOOR": "MOOR"},
    {"MOORINGS": "MOORINGS"},
    {"MOORS": "MOORS"},
    {"MOSS": "MOSS"},
    {"MOUNT": "MOUNT"},
    {"MYNYDD": "MYNYDD"},
    {"NANT": "NANT"},
    {"NEST": "NEST"},
    {"NOOK": "NOOK"},
    {"NURSERIES": "NURSERIES"},
    {"NURSERY": "NURSERY"},
    {"OAK": "OAK"},
    {"OAKS": "OAKS"},
    {"ORCHARD": "ORCHARD"},
    {"ORCHARDS": "ORCHARDS"},
    {"OUTLOOK": "OUTLOOK"},
    {"OVAL": "OVAL"},
    {"PADDOCK": "PADDOCK"},
    {"PADDOCKS": "PADDOCKS"},
    {"PANT": "PANT"},
    {"PARADE": "PARADE"},
    {"PARC": "PARC"},
    {"PARK": "PARK"},
    {"PARKS": "PARKS"},
    {"PARKWAY": "PARKWAY"},
    {"PASS": "PASS"},
    {"PASSAGE": "PASSAGE"},
    {"PASTURE": "PASTURE"},
    {"PASTURES": "PASTURES"},
    {"PATCH": "PATCH"},
    {"PATH": "PATH"},
    {"PATHWAY": "PATHWAY"},
    {"PAVEMENT": "PAVEMENT"},
    {"PEAK": "PEAK"},
    {"PENTRE": "PENTRE"},
    {"PIECE": "PIECE"},
    {"PIER": "PIER"},
    {"PIKE": "PIKE"},
    {"PIKES": "PIKES"},
    {"PINE": "PINE"},
    {"PINES": "PINES"},
    {"PITCH": "PITCH"},
    {"PITS": "PITS"},
    {"PL": "PL"},
    {"PLACE": "PL"},
    {"PLAIN": "PLAIN"},
    {"PLAINS": "PLAINS"},
    {"PLANTATION": "PLANTATION"},
    {"PLAS": "PLAS"},
    {"PLATT": "PLATT"},
    {"PLATTS": "PLATTS"},
    {"PLOT": "PLOT"},
    {"POINT": "POINT"},
    {"POND": "POND"},
    {"PONDS": "PONDS"},
    {"POOL": "POOL"},
    {"PORT": "PORT"},
    {"PORTH": "PORTH"},
    {"POST": "POST"},
    {"POUND": "POUND"},
    {"PRECINCT": "PRECINCT"},
    {"PRIORS": "PRIORS"},
    {"PRIORY": "PRIORY"},
    {"PROMENADE": "PROMENADE"},
    {"PROSPECT": "PROSPECT"},
    {"PWLL": "PWLL"},
    {"QUADRANT": "QUADRANT"},
    {"QUARRY": "QUARRY"},
    {"QUAY": "QUAY"},
    {"QUAYS": "QUAYS"},
    {"RACE": "RACE"},
    {"RAKE": "RAKE"},
    {"RANGE": "RANGE"},
    {"RD": "RD"},
    {"ROAD": "RD"},
    {"REACH": "REACH"},
    {"RETREAT": "RETREAT"},
    {"RHIW": "RHIW"},
    {"RHOS": "RHOS"},
    {"RHYD": "RHYD"},
    {"RIDE": "RIDE"},
    {"RIDGE": "RIDGE"},
    {"RIDING": "RIDING"},
    {"RIGG": "RIGG"},
    {"RIGGS": "RIGGS"},
    {"RING": "RING"},
    {"RISE": "RISE"},
    {"RISING": "RISING"},
    {"RIVER": "RIVER"},
    {"ROCK": "ROCK"},
    {"ROCKS": "ROCKS"},
    {"ROUND": "ROUND"},
    {"ROUNDABOUT": "ROUNDABOUT"},
    {"ROW": "ROW"},
    {"ROYD": "ROYD"},
    {"RUN": "RUN"},
    {"SANDS": "SANDS"},
    {"SARN": "SARN"},
    {"SCAR": "SCAR"},
    {"SHORE": "SHORE"},
    {"SIDE": "SIDE"},
    {"SIDINGS": "SIDINGS"},
    {"SLADE": "SLADE"},
    {"SLOPE": "SLOPE"},
    {"SPINNEY": "SPINNEY"},
    {"SPRINGS": "SPRINGS"},
    {"SPUR": "SPUR"},
    {"SQUARE": "SQUARE"},
    {"SQ": "SQUARE"},
    {"ST": "ST"},
    {"STREET": "ST"},
    {"STABLES": "STABLES"},
    {"STEPS": "STEPS"},
    {"STILE": "STILE"},
    {"STOKE": "STOKE"},
    {"STRAND": "STRAND"},
    {"STREAM": "STREAM"},
    {"STRYD": "STRYD"},
    {"TARN": "TARN"},
    {"TERRACE": "TERRACE"},
    {"TERRACES": "TERRACES"},
    {"THICKET": "THICKET"},
    {"THORN": "THORN"},
    {"THORNE": "THORNE"},
    {"THORNS": "THORNS"},
    {"THOROUGHFARE": "THOROUGHFARE"},
    {"THORP": "THORP"},
    {"THORPE": "THORPE"},
    {"TOP": "TOP"},
    {"TOPS": "TOPS"},
    {"TOWER": "TOWER"},
    {"TOWERS": "TOWERS"},
    {"TOWN": "TOWN"},
    {"TRACK": "TRACK"},
    {"TRAETH": "TRAETH"},
    {"TRAIL": "TRAIL"},
    {"TREE": "TREE"},
    {"TREES": "TREES"},
    {"TURN": "TURN"},
    {"TWYN": "TWYN"},
    {"UCHAF": "UCHAF"},
    {"UCHEL": "UCHEL"},
    {"VALE": "VALE"},
    {"VALLEY": "VALLEY"},
    {"VIADUCT": "VIADUCT"},
    {"VIEW": "VIEW"},
    {"VIEWS": "VIEWS"},
    {"VILLA": "VILLA"},
    {"VILLAGE": "VILLAGE"},
    {"VILLAS": "VILLAS"},
    {"VISTA": "VISTA"},
    {"WALK": "WALK"},
    {"WALKS": "WALKS"},
    {"WALKWAY": "WALKWAY"},
    {"WALL": "WALL"},
    {"WALLS": "WALLS"},
    {"WARREN": "WARREN"},
    {"WATER": "WATER"},
    {"WAUN": "WAUN"},
    {"WAY": "WAY"},
    {"WAYE": "WAYE"},
    {"WELL": "WELL"},
    {"WERN": "WERN"},
    {"WHARF": "WHARF"},
    {"WICKS": "WICKS"},
    {"WOOD": "WOOD"},
    {"WOODS": "WOODS"},
    {"WYND": "WYND"},
    {"YARD": "YARD"},
    {"YSBYTY": "YSBYTY"},
]

UKSubBuildingDesignator = [
    {"APT": "APT"},
    {"APARTMENT": "APT"},
    {"FLAT": "FLAT"},
    {"STUDIO": "STUDIO"},
    {"ROOM": "ROOM"},
    {"ZONE": "ZONE"},
    {"NUMBER": "NUMBER"},
    {"FLOOR": "FLOOR"},
]

DASH_STRING = "-"

POUND_REGEX = "([A-Z]*)#([0-9A-Z-/]*)"
POUND_STRING = "#"

DELIMITER_PATTERN_MAP = {
    "COMMA": "(\\s?,\\s?)+",
    "CO": "\\bC/O\\b",
    "EXCLAMATION_MARK": "!",
    "OPEN_BRACKET": "[\\[\\{\\(]",
    "CLOSE_BRACKET": "[\\]\\}\\)]",
    "SPACE": "\\s+",
}


class Delimiter:
    def __init__(self, text="", start=0, type=None) -> None:
        self.text = text
        self.start = start
        self.end = start + len(text)
        self.type = type

    def Parse(self, text, start=None):
        if start == None:
            start = 0
        delimiters = []
        a = list(DELIMITER_PATTERN_MAP.keys())
        for i in range(0, len(a)):
            delimiterType = a[i]
            newFoundDelimiters = self.findDelimiters(
                text, start, delimiters, delimiterType
            )
            delimiters.extend(newFoundDelimiters)
            delimiters.sort(key=lambda x: x.start, reverse=False)
        return delimiters

    def findDelimiters(self, text, start, delimiters, type):
        result = []
        textStart = start
        delimiters_1 = delimiters

        for i in range(0, len(delimiters_1)):
            curDelimiter = delimiters_1[i]
            textEnd = curDelimiter.start
            if textEnd == textStart:
                textStart = curDelimiter.end
                continue
            searchString = text[textStart - start : textEnd - start]
            regexp = re.compile(DELIMITER_PATTERN_MAP[type], re.IGNORECASE)
            matchResult = 0
            for matchResult in finditer(regexp, searchString):
                delimiter = Delimiter(
                    matchResult.group(),
                    textStart + matchResult.span()[0],
                    type,
                )
                result.append(delimiter)
            textStart = curDelimiter.end

        if textStart < start + len(text):
            searchString = text[textStart - start :]
            regexp = re.compile(DELIMITER_PATTERN_MAP[type], re.IGNORECASE)
            matchResult = 0
            for matchResult in finditer(regexp, searchString):
                index = matchResult.span()[0]
                delimiterString = matchResult.group()
                delimiter = Delimiter(delimiterString, textStart + index, type)
                result.append(delimiter)
        return result


class NormalizedAddress:
    def __init__(self, fullAddress):
        self.fullAddress = fullAddress
        self.addressTokens = []

    def generateTokens(self):
        delimiters = Delimiter().Parse(text=self.fullAddress)
        tokens = []
        start = 0
        address = self.fullAddress
        textStart = start

        delimiters_1 = delimiters

        for i in range(0, len(delimiters_1)):
            delimiter = delimiters_1[i]
            textEnd = delimiter.start
            if textEnd != textStart:
                addressToken = address[textStart - start : textEnd - start]
                tokens.append(addressToken)
            textStart = delimiter.end
        if textStart < start + len(address):
            addressToken = address[textStart - start :]
            tokens.append(addressToken)

        self.addressTokens = tokens

    def updateAddressTokens(self, index, deleteCount, **kwargs):
        rest = []

        for key, value in kwargs.items():
            rest.append(value)

        self.addressTokens.pop(index)
        for i in range(0, len(rest)):
            self.addressTokens.insert(index + i, rest[i])


class Dash:
    def apply(self, normalizedAddress):
        for i in range(0, len(normalizedAddress.addressTokens)):
            word = normalizedAddress.addressTokens[i]
            index = word.rfind(DASH_STRING)
            if index > 0 and index < len(word) - 1:
                firstPart = word[0:index]
                secondPart = word[index + 1 :]
                if not secondPart.isnumeric() and firstPart.isnumeric():
                    normalizedAddress.updateAddressTokens(
                        i, 1, first_part=firstPart, second_part=secondPart
                    )


class Pound:
    def apply(self, normalizedAddress):
        for i in range(0, len(normalizedAddress.addressTokens)):
            word = normalizedAddress.addressTokens[i]
            regexp = re.compile(POUND_REGEX)
            matchResult = 0
            for matchResult in finditer(regexp, word):
                firstPart = matchResult.group(1)
                secondPart = matchResult.group(2)

                if firstPart == "" and secondPart == "":
                    continue

                if firstPart == "":
                    normalizedAddress.updateAddressTokens(
                        i, 1, pound_string=POUND_STRING, second_part=secondPart
                    )
                    i += 1
                elif secondPart == "":
                    normalizedAddress.updateAddressTokens(
                        i, 1, first_part=firstPart, pound_string=POUND_STRING
                    )
                    i += 1
                else:
                    normalizedAddress.updateAddressTokens(
                        i,
                        1,
                        first_part=firstPart,
                        pound_string=POUND_STRING,
                        second_part=secondPart,
                    )
                    i += 2


preproccessRules = [Dash(), Pound()]


class AddressNormalizer:
    def __init__(self, countryCode):
        self.streetWordMaps = []
        self.streetWordMaps.extend(NumberIndicators)
        self.streetWordMaps.extend(DirectionalWords)
        self.normalizedAddress = None
        self.sha256normalizedAddress = None

        if countryCode == "US":
            self.streetWordMaps.extend(USStreetSuffixes)
            self.streetWordMaps.extend(USSubBuildingDesignator)

        elif countryCode == "CA":
            self.streetWordMaps.extend(DefaultStreetSuffixes)

        elif countryCode == "UK":
            self.streetWordMaps.extend(UKOrganizationSuffixes)
            self.streetWordMaps.extend(UKStreetSuffixes)
            self.streetWordMaps.extend(UKSubBuildingDesignator)

        elif countryCode == "FR":
            self.streetWordMaps.extend(FRStreetDesignator)
            self.streetWordMaps.extend(DefaultStreetSuffixes)

        elif countryCode == "DE":
            self.streetWordMaps.extend(DefaultStreetSuffixes)

        elif countryCode == "ES":
            self.streetWordMaps.extend(DefaultStreetSuffixes)
            self.streetWordMaps.extend(ESStreetPrefixes)

        elif countryCode == "IT":
            self.streetWordMaps.extend(DefaultStreetSuffixes)
            self.streetWordMaps.extend(ITStreetPrefixes)

        elif countryCode == "JP":
            self.streetWordMaps.extend(DefaultStreetSuffixes)

        elif countryCode == "IN":
            self.streetWordMaps.extend(DefaultStreetSuffixes)

        else:
            raise ValueError("The country code provided is not yet supported")

        self.preproccessRules = preproccessRules

    def normalize(self, record):
        record = record.strip().upper()

        normalizedAddress = NormalizedAddress(record)
        normalizedAddress.generateTokens()

        a = self.preproccessRules
        for i in range(0, len(a)):
            rule = a[i]
            rule.apply(normalizedAddress)

        for i in range(0, len(normalizedAddress.addressTokens)):
            word = normalizedAddress.addressTokens[i]
            for j in range(0, len(self.streetWordMaps)):
                if word in self.streetWordMaps[j]:
                    normalizedAddress.updateAddressTokens(
                        i, 1, first_part=self.streetWordMaps[j].get(word)
                    )

        self.normalizedAddress = "".join(
            normalizedAddress.addressTokens
        ).lower()
        self.sha256normalizedAddress = hashlib.sha256(
            self.normalizedAddress.encode()
        ).hexdigest()
        return self
