repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      args: ['--unsafe']
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args:
      - --autofix
      - --no-sort-keys
      exclude: (?x)^(
                docs/sample_data/sample_dimension.json|
                docs/sample_data/sample_fact.json|
        )$
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      files: "\\.(py)$"
      args: [--settings-path=pyproject.toml]

-  repo: https://github.com/pycqa/flake8
   rev: 6.0.0
   hooks:
   - id: flake8
     additional_dependencies:
     - flake8-bugbear
     exclude: ^source/tests/

-  repo: https://github.com/pycqa/pylint
   rev: v2.16.1
   hooks:
    - id: pylint
      exclude: ^source/tests/
